name: mbuild-tutorials

channels:
  - conda-forge

dependencies:
  - python>=3.6
  - numpy
  - scipy
  - packmol>=1!18.013
  - nglview>=0.6.2.3
  - parmed
  - mdtraj
  - gsd
  - openbabel
  - rdkit
  - jupyter
  - nbformat
  - foyer
  - py3Dmol
  - pytest
  - nbval
