name: mbuild-binder

channels:
  - conda-forge

dependencies:
  - python>=3.6
  - numpy
  - scipy
  - packmol>=20
  - nglview>=3
  - parmed
  - mdtraj
  - gsd
  - openbabel
  - rdkit
  - jupyter
  - nbformat
  - mbuild
  - foyer
  - py3Dmol
